name: kitty_azumo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.2
  test: ^1.17.10
  retrofit: ^3.0.1+1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator:

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
